const user = {
  login: "teyouale",
  id: 51370727,
  node_id: "MDQ6VXNlcjUxMzcwNzI3",
  avatar_url: "https://avatars.githubusercontent.com/u/51370727?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/teyouale",
  html_url: "https://github.com/teyouale",
  followers_url: "https://api.github.com/users/teyouale/followers",
  following_url: "https://api.github.com/users/teyouale/following{/other_user}",
  gists_url: "https://api.github.com/users/teyouale/gists{/gist_id}",
  starred_url: "https://api.github.com/users/teyouale/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/teyouale/subscriptions",
  organizations_url: "https://api.github.com/users/teyouale/orgs",
  repos_url: "https://api.github.com/users/teyouale/repos",
  events_url: "https://api.github.com/users/teyouale/events{/privacy}",
  received_events_url: "https://api.github.com/users/teyouale/received_events",
  type: "User",
  site_admin: false,
  name: null,
  company: null,
  blog: "",
  location: "Addis Ababa,Ethiopia",
  email: null,
  hireable: null,
  bio: "Working With React and Learning Machine Language with Python",
  twitter_username: null,
  public_repos: 14,
  public_gists: 0,
  followers: 0,
  following: 1,
  created_at: "2019-06-04T13:06:13Z",
  updated_at: "2021-03-23T21:16:02Z",
};

export function getUser() {
  return user;
}
